const GET_WEB_APP_INFO = "GET_WEB_APP_INFO";
const GET_WEB_APP_INFO_SUCCESS = "GET_WEB_APP_INFO_SUCCESS";

const UPDATE_PROGRESS_BAR = "UPDATE_PROGRESS_BAR";

const FOCUS_MAIN_WINDOW = "FOCUS_MAIN_WINDOW";

const SAVE_FILE = "SAVE_FILE";
const OPEN_FILE = "OPEN_FILE";

const OPEN_IN_BROWSER = "OPEN_IN_BROWSER";

const DOWNLOAD_EXTENSION = "DOWNLOAD_EXTENSION";

module.exports = {
  GET_WEB_APP_INFO,
  GET_WEB_APP_INFO_SUCCESS,
  UPDATE_PROGRESS_BAR,
  SAVE_FILE,
  OPEN_FILE,
  OPEN_IN_BROWSER,
  FOCUS_MAIN_WINDOW,
  DOWNLOAD_EXTENSION
};
